env: "local" #demo, prod
#storage_path: "./storage/sso.db" # for sqlite
storage_path: "postgresql://postgres:postgres@127.0.0.1:5000/postgres"
storage_patroni:
  master: "postgresql://postgres:postgres@127.0.0.1:5000/postgres"
  slave: "postgresql://postgres:postgres@127.0.0.1:5001/postgres"
access_token_ttl: 1h
refresh_token_ttl: 240h # 10 days
service_secret: "service very secret"
grpc:
  port: 44044
  timeout: 10h
redis_address: "localhost:6379" # in case of redis usage insted of redis_sentinel
redis_sentinel:
  masterName: "mymaster"
  sentinelAddrs1: "localhost:26379"
  sentinelAddrs2: "localhost:26380"
  sentinelAddrs3: "localhost:26381"
  password: "123456"
jaeger_url: "http://localhost:14268/api/traces"